# Using NumPy


Once you've installed NumPy you can import it as a library:

In [1]:
import numpy as np


In [2]:
my_list=[1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# arange


In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

# Zeors and ones


In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones(3)

array([1., 1., 1.])

In [11]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# Linspace

In [12]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [13]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [14]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

# eye

it is use for identity matrix

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

Random
Numpy also has lots of ways to create random number arrays:

rand
Creates an array of the given shape and populates it with random samples from a uniform distribution over [0, 1)

In [18]:
np.random.rand(2)

array([0.77338669, 0.44596797])

In [19]:
np.random.rand(5,5)

array([[0.57516199, 0.0737021 , 0.4784854 , 0.55448497, 0.62002589],
       [0.33563993, 0.18812426, 0.27282674, 0.49317119, 0.20600738],
       [0.55517457, 0.10760794, 0.1320168 , 0.70748491, 0.26853886],
       [0.17234538, 0.81354484, 0.03047338, 0.70684719, 0.79589392],
       [0.63727558, 0.57922941, 0.3129678 , 0.20175102, 0.77326249]])

# randn
Returns a sample (or samples) from the "standard normal" distribution [σ = 1]. Unlike rand which is uniform, values closer to zero are more likely to appear.

In [20]:
np.random.randn(2)

array([-0.3929739 , -0.06166374])

In [21]:
np.random.randn(5,5)

array([[-0.31295533, -0.44661743, -0.89584982, -0.31457251, -0.93387995],
       [ 1.78396305, -0.17229629,  0.90914725,  0.41996046,  0.26903235],
       [-3.45869379, -0.15010115,  1.03387894,  0.8954578 ,  0.62995572],
       [-0.26010083, -1.78508539, -1.15345052,  2.05060059, -0.01118971],
       [ 1.2151628 , -0.59900295, -0.50432892, -0.01950461,  0.42423024]])

# randint
Returns random integers from low (inclusive) to high (exclusive)

In [22]:
np.random.randint(1,100)

99

In [23]:
np.random.randint(1,100,10)

array([10, 77, 31,  6, 34, 99, 99, 82, 45, 36])

# seed
Can be used to set the random state, so that the same "random" results can be reproduced

In [24]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [25]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])